require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'matterapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'matterappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
  # flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  #pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  #pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  #pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
end

target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 8.15.0'
end

target 'matterapp-tvOS' do
  # Pods for matterapp-tvOS

  target 'matterapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
