const genders = [
  'Male',
  'Female',
  'Transgender',
  'Genderqueer',
  'Questioning',
  'Agender',
  'Aliagender',
  'Androgyne',
  'Aporagender',
  'Bigender',
  'Boi',
  'Butch',
  'Demiboy',
  'Demigirl',
  'Demiby',
  'Demitrans',
  'Gender fluid',
  'Gender neutral',
  'Gender nonconforming',
  'Gender variant',
  'Intersex Man',
  'Intersex Woman',
  'Neither',
  'Neutrois',
  'Novigender',
  'Pangender',
  'Polygender',
  'Trans female',
  'Trans man',
  'Trans person',
  'Transfeminine',
  'Transmasculine',
  'Transsexual',
  'Trigender',
  'Two-spirit',
  'Other',
];

export default genders;
