export const seedCards = [
  {
    type: "hobby",
    content: '\"I like Calligraphy, Running, Knitting\"',
    content_type: "text",
    groupable: false,    
  },
  {
    type: "movie",
    content: '{\"adult\":false,\"backdrop_path\":\"/cjaOSjsjV6cl3uXdJqimktT880L.jpg\",\"genre_ids\":[10751,14,16,35],\"id\":529203,\"original_language\":\"en\",\"original_title\":\"The Croods: A New Age\",\"overview\":\"Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family thats a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.\",\"popularity\":916.853,\"poster_path\":\"/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg\",\"release_date\":\"2020-11-25\",\"title\":\"The Croods: A New Age\",\"video\":false,\"vote_average\":7.5,\"vote_count\":1907,\"cast\":\"Nicolas Cage\",\"director\":\"Joel Crawford\"}',
    content_type: "image",
    groupable: true,    
  },
  {
    type: "movie",
    content: '{\"adult\":false,\"backdrop_path\":\"/z3ElnHwcf1g56Qlp53yGbPsGXL7.jpg\",\"genre_ids\":[28,12,878,14,53],\"id\":76600,\"original_language\":\"en\",\"original_title\":\"Avatar 2\",\"overview\":\"Avatar: The Way of Water will once again follow Sam Worthington’s Jake Sully twelve years after exploring Pandora and joining the Na’vi. He has since raised a family with Neytiri, portrayed by Zoe Saldana, and established himself within the clans of the new world. Of course, peace can only last so long. Especially when the military organisation from the original film returns to “finish what they started”.\",\"popularity\":63.074,\"poster_path\":\"/110CYDvtnVRWs9meC4lsZCz98vg.jpg\",\"release_date\":\"2022-12-14\",\"title\":\"Avatar 2\",\"video\":false,\"vote_average\":0,\"vote_count\":0,\"cast\":\"Sam Worthington\",\"director\":\"James Cameron\"}',
    content_type: "image",
    groupable: true,    
  },
  {
    type: "music",
    content: '{\"name\":\"Billie Jean\",\"image\":\"https://i.scdn.co/image/ab67616d0000b2734121faee8df82c526cbab2be\",\"artist\":\"Michael Jackson\",\"preview_url\":\"https://p.scdn.co/mp3-preview/f504e6b8e037771318656394f532dede4f9bcaea?cid=5afcf1483efc4381928cf718f255bf71\"}',
    content_type: "image",
    groupable: true,    
  },
  {
    type: "music",
    content: '{\"name\":\"Hey Jude (Arr. T. Takemitsu)\",\"image\":\"https://i.scdn.co/image/ab67616d0000b27342ed9835d2d43e77cfe41ac7\",\"artist\":\"John Lennon\",\"preview_url\":\"https://p.scdn.co/mp3-preview/9b754c1479db5f124a2e9c0f390aae43c0f8f383?cid=5afcf1483efc4381928cf718f255bf71\"}',
    content_type: "image",
    groupable: true,    
  },
  {
    type: "music",
    content: '{\"name\":\"Money Longer\",\"image\":\"https://i.scdn.co/image/ab67616d0000b2738be07181aa935225a6f25d56\",\"artist\":\"Lil Uzi Vert\",\"preview_url\":\"https://p.scdn.co/mp3-preview/d3e64e38a6bc9be041fe7b1d6c9a0cacf07e2955?cid=5afcf1483efc4381928cf718f255bf71\"}',
    content_type: "image",
    groupable: true,    
  },
  {
    type: "image_prompt",
    content: '{\"question\":\"what is the achivement?\",\"answer\":\"Continuous Journey\",\"image\":\"HjcDQE21cPvx6qvROrdQ\"}',
    content_type: "image",
    groupable: false,    
  },
  {
    type: "prompt",
    content: '{\"question\":\"Do you have a type? If so, what is it?\",\"answer\":\"Kind\"}',
    content_type: "text",
    groupable: false,    
  },
  {
    type: "prompt",
    content: '{\"question\":\"how do you fall in love with someone?\",\"answer\":\"Attitude & Eye contact\"}',
    content_type: "text",
    groupable: false,    
  },
  {
    type: "instagram",
    content: '{\"igm_token\":\"IGQVJXWGVROG5yY2V6cE5VZAE5OdjZAibEdhaEdCeWJnX1A1YUhwZAmp3cW5LNFlrT1plRG9vdV81WU9KNFBEODVyeFNja0R5WkRTaTJWMmo4NFNCV3dTRlE2U1FSWjJ4djFKTEQ0TDRR\"}',
    content_type: "image",
    groupable: false,    
  },
];

export const infos = [
  //Credentials
  {
    type: "info",
    category_slug: "Credentials",
    option_list: ["Occupation"],
    question: "Occupation",
    option_type: "multi_input",
      long_question: "What is you occupation?",
      priority: 10,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Credentials",
    option_list: ["School", "2nd School", "3rd School"],
    question: "School",
    option_type: "multi_input",
      long_question: "Where did you go to school?",
      priority: 9,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Credentials",
    option_list: ["High School Diploma","Trade/Tech School","Currently in College","Undergraduate Degree","Currently in Grad School","Graduate Degree","PhD / Doctorate","I'd rather not say"],
    question: "Education level",
    option_type: "select",
      long_question: "What's your education level?",
      priority: 8,
      editable: true,
      hidable: false,
  }, 
  {
    type: "info",
    category_slug: "Credentials",
    option_list: ["Country", "City/Town"],
    question: "Hometown",
    option_type: "multi_input",
      long_question: "What's your hometown?",
      priority: 7,
      editable: true,
      hidable: true,
  }, 
  //Primary
  {
    type: "info",
    category_slug: "Primary",
    option_list: [],
    question: "Name",
    option_type: "text",
      long_question: "What's your name?",
      priority: 10,
      editable: true,
      hidable: false,
  }, 
  {
    type: "info",
    category_slug: "Primary",
    option_list: [],
    question: "Birthday",
    option_type: "date",
      long_question: "What's your birthday?",
      priority: 9,
      editable: true,
      hidable: false,
  }, 
  {
    type: "info",
    category_slug: "Primary",
    option_list: [    'Male',
      'Female',
      'Transgender',
      'Genderqueer',
      'Questioning',
      'Agender',
      'Aliagender',
      'Androgyne',
      'Aporagender',
      'Bigender',
      'Boi',
      'Butch',
      'Demiboy',
      'Demigirl',
      'Demiby',
      'Demitrans',
      'Gender fluid',
      'Gender neutral', 
      'Gender nonconforming',
      'Gender variant',
      'Intersex Man',
      'Intersex Woman',
      'Neither',
      'Neutrois',
      'Novigender',
      'Pangender',
      'Polygender',
      'Trans female',
      'Trans man',
      'Trans person',
      'Transfeminine',
      'Transmasculine',
      'Transsexual',
      'Trigender',
      'Two-spirit',
      'Other',
  ],
    question: "Gender",
    option_type: "select",
      long_question: "What's your gender?",
      priority: 8,
      editable: true,
      hidable: false,
  }, 
  {
    type: "info",
    category_slug: "Primary",
    option_list: [],
    question: "Location",
    option_type: "location",
      long_question: "Set your location",
      priority: 8,
      editable: false,
      hidable: false,
  }, 
  {
    type: "info",
    category_slug: "Primary",
    option_list: ["American Indian", "Western European", "Eastern European", "Scandinavian", "East Asian", "Middle Eastern", "South Asian", "African Descent", "Hispanic / Latino", "Pacific Islander", "White / Caucasian", "Other"],
    question: "Ethnicity",
    option_type: "select",
      long_question: "What's your ethnicity?",
      priority: 7,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Primary",
    option_list: ["cm", "ft", "inch"],
    question: "Height",
    option_type: "height",
      long_question: "What's your height?",
      priority: 6,
      editable: true,
      hidable: true,
  }, 
  //Lifestyle
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Bahai","Buddhist","Catholic","Christian","Hindu","Jain","Jewish","Shaman","Muslim","Spiritual","Agnostic","Atheist","Zoroastrain","Sikh","Other"],
    question: "Religion",
    option_type: "select",
      long_question: "What's your religion?",
      priority: 10,
      editable: true,
      hidable: true,

  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Liberal", "Moderate", "Conservative", "Apolitical","Other"],
    question: "Politics",
    option_type: "select",
      long_question: "",
      priority: 9,
      editable: true,
      hidable: true,
  },
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Have", "Don't have", "I'd rather not say"],
    question: "Have children",
    option_type: "select",
      long_question: "Do you have children?",
      priority: 8,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Yes", "No", "Maybe", "Not sure"],
    question: "Want children",
    option_type: "select",
      long_question: "Do you want children in the future?",
      priority: 7,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Aries", "Taurus", "Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"],
    question: "Zodiac sign",
    option_type: "select",
    long_question: "Zodiac sign",
    priority: 6,
    editable: true,
    hidable: true,
  },
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Enjoy Drinks", "Socially", "Rarely", "No"],
    question: "Drinking",
    option_type: "select",
      long_question: "Do you drink?",
      priority: 5,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Regularly", "Socially", "No"],
    question: "Smoking",
    option_type: "select",
      long_question: "Do you smoke?",
      priority: 4,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Regularly", "Socially", "No"],
    question: "Marijuana use",
    option_type: "select",
      long_question: "Do you use marijuana?",
      priority: 3,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Yes", "Sometimes", "No"],
    question: "Drug use",
    option_type: "select",
      long_question: "Do you use drug?",
      priority: 2,
      editable: true,
      hidable: true,
  }, 
  {
    type: "info",
    category_slug: "Lifestyle",
    option_list: ["Active", "Sometimes", "Almost never"],
    question: "Exercise",
    option_type: "select",
    long_question: "Exercise",
    priority: 1,
    editable: true,
    hidable: true,
  },
  ];

  export const preferences = [
    {
      type: "preference",
      category_slug: "Primary",
      option_list: ["male", "female", "everyone"],
      question: "Looking for",
      option_type: "multi_select",
      long_question: "Who are you looking for",
      long_long_question: "",
      priority: 10,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Primary",
      option_list: ["false", "true"],
      question: "Global mode",
      option_type: "switch",
      long_question: "Turn on global mode",
      long_long_question: "Do you wish to turn on the global mode?",
      priority: 9,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Primary",
      option_list: ["max_range"],
      question: "Max distance",
      option_type: "slider",
      long_question: "Maximium Distance",
      long_long_question: "What’s your ideal max distance for finding a date?",
      priority: 8,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Primary",
      option_list: ["min_range", "max_range"],
      question: "Age range",
      option_type: "slider",
      long_question: "Age range",
      long_long_question: "What’s your age preference?",
      priority: 7,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Primary",
      option_list: ["min_range", "max_range"],
      question: "Height",
      option_type: "slider",
      long_question: "Height",
      long_long_question: "What’s your height preference?",
      priority: 6,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Secondary",
      option_list: ["American Indian", "Western European", "Eastern European", "Scandinavian", "East Asian", "Middle Eastern", "South Asian", "African Descent", "Hispanic / Latino", "Pacific Islander", "White / Caucasian", "Other", "Open to All"],
      question: "Ethnicity",
      option_type: "multi_select",
      long_question: "Ethnicity",
      long_long_question: "What’s your preference on ethnicity?",
      priority: 10,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Secondary",
      option_list: ["Bahai","Buddhist","Catholic","Christian","Hindu","Jain","Jewish","Shaman","Muslim","Spiritual","Agnostic","Atheist","Zoroastrain","Sikh","Other","Open to All"],
      question: "Religion",
      option_type: "multi_select",
      long_question: "Religion",
      long_long_question: "What’s your preference on religion?",
      priority: 9,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Secondary",
      option_list: ["Liberal", "Moderate", "Conservative", "Apolitical","Other","Open to All"],
      question: "Politics",
      option_type: "multi_select",
      long_question: "Politics",
      long_long_question: "What’s your preference on politics?",
      priority: 8,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Secondary",
      option_list: ["High School Diploma","Trade/Tech School","Currently in College","Undergraduate Degree","Currently in Grad School","Graduate Degree","PhD / Doctorate"],
      question: "Education level",
      option_type: "multi_select",
      long_question: "Education level",
      long_long_question: "What’s your preference on education level?",
      priority: 7,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Secondary",
      option_list: ["Aries", "Taurus", "Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces","Open to All"],
      question: "Zodiac sign",
      option_type: "multi_select",
      long_question: "Zodiac sign",
      long_long_question: "",
      priority: 3,
      editable: true
    },

    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Have", "Don't have", "Open to All"],
      question: "Have children",
      option_type: "select",
      long_question: "Have children",
      long_long_question: "Can a potential match have children?",
      priority: 10,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Yes", "No", "Open to All"],
      question: "Want children",
      option_type: "select",
      long_question: "Want children",
      long_long_question: "Can a potential match want children?",
      priority: 9,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Enjoy Drinks", "Socially", "Rarely", "No", "Open to All"],
      question: "Drinking",
      option_type: "multi_select",
      long_question: "Drinking",
      long_long_question: "Can a potential match be a drinker?",
      priority: 8,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Regularly", "Socially", "No", "Open to All"],
      question: "Smoking",
      option_type: "multi_select",
      long_question: "Smoking",
      long_long_question: "Can a potential match be a smoker?",
      priority: 7,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Regularly", "Socially", "No", "Open to All"],
      question: "Marijuana use",
      option_type: "multi_select",
      long_question: "Marijuana",
      long_long_question: "Can a potential match be a marijuana user?",
      priority: 6,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Yes", "Sometimes", "No", "Open to All"],
      question: "Drug use",
      option_type: "multi_select",
      long_question: "Drug use",
      long_long_question: "Can a potential match be a drug user?",
      priority: 5,
      editable: true
    },
    {
      type: "preference",
      category_slug: "Lifestyle",
      option_list: ["Active", "Sometimes", "Almost never", "Open to All"],
      question: "Exercise",
      option_type: "multi_select",
      long_question: "Exercise",
      long_long_question: "What's your preference on their lifestyle",
      priority: 4,
      editable: true
    },
];

export const hobbies = [
  {
    type: "hobby",
    category_slug: "art",
    question: "Calligraphy",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "art",
    question: "Art & crafts",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 99,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "chill",
    question: "Video games",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 98,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "chill",
    question: "Watching sports",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 97,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "chill",
    question: "Camping",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 96,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "chill",
    question: "Birdwatching",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 95,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "creativity",
    question: "Collectives",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 94,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "creativity",
    question: "Knitting",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 93,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "Reading",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 92,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "Writing",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 91,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "Technology",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 90,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "History",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 89,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "Chess",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 88,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "education",
    question: "New language",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 87,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "entertainment",
    question: "Music",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 86,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "entertainment",
    question: "Travel",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 85,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "entertainment",
    question: "Photography",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 84,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "fun",
    question: "Puzzles",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 83,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "health",
    question: "Meditation",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 81,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "hustle",
    question: "Pottery",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 80,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "hustle",
    question: "Trading & investing",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 79,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "social science",
    question: "Cooking",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 78,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "social science",
    question: "Pets",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 77,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "social science",
    question: "Gardening",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 76,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "social science",
    question: "Volunteer",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 75,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Hiking",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 74,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Fitness",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 73,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Playing sports",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 72,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Dancing",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 71,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Running",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 70,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Rock climbing",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 69,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Swimming",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 68,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Yoga",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 67,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Tennis",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 66,
    editable: true
  },
  {
    type: "hobby",
    category_slug: "sports",
    question: "Volleyball",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 65,
    editable: true
  },
]

export const prompts = [
  {
    type: "prompt",
    category_slug: "Personality",
    question: "If you could wake up tomorrow having gained any one quality or character, what would it be? Why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What do you value the most in a friendship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's the one thing that you wish your future date to know about you?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What are some things you want to accomplish before you die?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's the biggest goal you are working toward right now?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's something people are always surprised to learn about you?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What would your friends and family say as one of your defining personality traits?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "My best friends would describe me as…",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's your Myers-Briggs personality type? Do you agree with it?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's one thing that only close friends know about you?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "If your life was a movie, what would it be called? Why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What’s the most stereotypical thing you fall under for your zodiac sign?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's the question people ask you most often?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What’s your go-to party trick?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What's something embarrassing that you have done?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What makes you feel empowered?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What something that you’re embarrassed you’re so good at?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What color would you use to describe yourself and why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What is the most adventurous thing you've done?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Personality",
    question: "What are your personal goals for the next few years?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's your love language?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "Describe your ideal date night",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "A pro and con of dating me...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's a dealbreaker for you in a relationship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "Things that make a relationship great are...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "Character and qualities that I admire the most in a partner are...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What is your go to date spot? ",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's the most romantic thing you've ever experienced?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's your goal in a relationship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "How will you know when you’ve found the one?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What’s something you find attractive that others usually don't?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's your biggest fear in a relationship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What's your favorite thing about being in a relationship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "Do you have a type? If so, what is it?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What are some of your biggest turn-offs?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What are your ground rules for dating?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "The type of relationship I am looking for is...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "What quirky qualities do you find endearing?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "Do you think it's important for partners to be more similar or different in a relationship?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Relationship",
    question: "The funnies date story...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "Does pineapple belong on pizza? Why or why not?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "Two truths and a lie about me...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What's your go to drink at a party?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What’s something that always makes you laugh?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What was your best Halloween costume?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What would your stripper name be and why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What’s the funniest pick up line you’ve heard?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What would the adult version of an ice-cream truck sell and what song would it play?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "Come up with the funniest superpower and describe how it works",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "You’re stranded on an island and you can only bring 3 things? What are they (wrong answers only)?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What’s the weirdest talent you have?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What’s the weirdest conversation you’ve eavesdropped on?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "If you could eat dinner with 3 famous people dead or alive, who would you choose?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What kind of secret society would you like to start?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What would be the creepiest thing you could say while passing a stranger on the street?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "If there is a fire and you can save only 3 objects from your home, what would you save?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "Come up with the funnies app. How would it work?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What animal would be the most terrifying if it could speak? Why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What’s the dumbest thing someone has argued with you about?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Fun & Quirky",
    question: "What's your most irrational fear?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What was your funniest travel story?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "If you get all paid vacation anywhere in the world, where would you go?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "Money aside, what is your dream vacation?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "Describe the most interesting person you met while traveling",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What do you like to do when you visit a new country?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "On your last vacation, where did you go, and what did you do?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What was your best travel memory?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What's the coolest thing you have ever done when you visit a new place?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "How would you survive if you were stranded on an island?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "​Tell your worst travel story",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "When traveling, do you like to plan everything out or just see what happens?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What has been your favorite souvenir you have bought? ",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "A travel destination you can never get sick of and why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "Do you prefer trips in nature or to cities?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "Craziest night you've ever had in another country?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What is your dream road trip?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What is the best kept secret in your city?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "Best way to spend a day in your city?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "The worst trouble you got yourself into while traveling?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Travel",
    question: "What's is the most beautiful place you've been?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What is your personal philosophy?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "Who is your role model? Why?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What's the meaning of life?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What really matters to me is ...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 1000,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What are your deepest fears?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "For you, what does it mean to be happy?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "If you knew that you will die in one year, would you change the way you are living now?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What do you love the most about yourself?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "If you had all the resources and land available, what would you build there?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What advice would you give your younger self?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What’s one thing that you cannot live without?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "If you had 24 hours to live what would you do? Who would you be with?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What are your core values?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "If a crystal ball could tell you one thing about your future, what would you want to know?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "Life is beautiful because...",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What excites you the most about the future?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What's a controversial opinion you have?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What's your favorite quote?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What social stigma does society need to get over?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
  {
    type: "prompt",
    category_slug: "Perspective",
    question: "What are you super-opinionated about?",
    option_list: [],
    option_type: "",
    long_question: "",
    priority: 100,
    editable: true
  },
]